# Generated by Django 3.0.3 on 2020-11-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecartApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='mobile_number',
        ),
    ]
