# Generated by Django 3.0.3 on 2020-11-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecartApp', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_description',
            field=models.CharField(default=0, max_length=260),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='item_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
