# Generated by Django 3.0.3 on 2020-11-22 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecartApp', '0002_generateitem_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('generateitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecartApp.GenerateItem')),
            ],
            bases=('ecartApp.generateitem',),
        ),
    ]
