# Generated by Django 3.0.3 on 2020-11-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecartApp', '0003_auto_20201122_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_url',
        ),
    ]
